title: "Adrian Dominguez Castro, PhD"
description: "Data Scientist | Machine Learning | Artificial Intelligence"
theme: minima
author: "Adrian Dominguez Castro, PhD"

# Optional settings
show_excerpts: true
