title: "Adrian Dominguez Castro, PhD"
description: "Data Scientist | Machine Learning "
theme: minima
author: Adrian Dominguez Castro, PhD

nav:
  - Home: index.md
  - Projects: projects.md
  - CV: cv.md
  - Publications: publications.md
  - Contact: contact.md
