title: "Adrian Dominguez Castro, PhD"
description: "This is the personal website of Dr. Adrian Dominguez Castro"
theme: minima
author: " "

header_pages:
  - portfolio.md
  - publications.md
  - cv.md
  - contact.md

