title: "Adrian Dominguez Castro, Ph.D."
description: "This is the personal website of  X    Dr.Adrian Dominguez Castro"
              
theme: minima
author: " "

header_pages:
  - portfolio.md
  - publications.md
  - cv.md
  - contact.md

