title: "Personal Website"
description: "Data Scientist | Machine Learning"
theme: minima
author: Adrian Dominguez Castro, PhD

header_pages:
  - portfolio.md
  - publications.md
  - GitHub.md
  - LinkedIn.md
  - cv.md
  - contact.md

