title: "Personal Website"
description: "Data Scientist | Machine Learning "
theme: minima
author: Adrian Dominguez Castro, PhD

nav:
  - Home: index.md
  - Portfolio: projects.md
  - Publications: publications.md
  - CV: cv.md 
  - Contact: contact.md
